### ISSUE TITLE
new tag with `cookie_samesite`

### ISSUE THREAD

**Issue by fejjo** [diablomedia/zf1-session#99]
Hi, could I ask for you to release a new tag with the latest changes https://github.com/diablomedia/zf1-session/pull/98.

Thank you for your help :)

**Comment by jaydiablo** [comment]
@fejjo yeah, we're working on tagging all of the updates we've done over the last few days to all of the ZF1 packages, just double checking some tests in our apps and making sure nothing is amiss. Should have a new tag soon.

**Comment by fejjo** [comment]
Great, thank you @jaydiablo :)

**Comment by tomasfejfar** [comment]
Woot! 🎉
